export interface Surah {
  no:      number
  nama:    string   // nama Indonesia / transliterasi
  maxAyat: number
}

/** Daftar 114 surah Al-Qur'an dengan jumlah ayat. */
export const SURAH_LIST: Surah[] = [
  { no:   1, nama: "Al-Fatihah",         maxAyat:   7 },
  { no:   2, nama: "Al-Baqarah",         maxAyat: 286 },
  { no:   3, nama: "Ali 'Imran",         maxAyat: 200 },
  { no:   4, nama: "An-Nisa'",           maxAyat: 176 },
  { no:   5, nama: "Al-Ma'idah",         maxAyat: 120 },
  { no:   6, nama: "Al-An'am",           maxAyat: 165 },
  { no:   7, nama: "Al-A'raf",           maxAyat: 206 },
  { no:   8, nama: "Al-Anfal",           maxAyat:  75 },
  { no:   9, nama: "At-Tawbah",          maxAyat: 129 },
  { no:  10, nama: "Yunus",              maxAyat: 109 },
  { no:  11, nama: "Hud",               maxAyat: 123 },
  { no:  12, nama: "Yusuf",             maxAyat: 111 },
  { no:  13, nama: "Ar-Ra'd",           maxAyat:  43 },
  { no:  14, nama: "Ibrahim",           maxAyat:  52 },
  { no:  15, nama: "Al-Hijr",           maxAyat:  99 },
  { no:  16, nama: "An-Nahl",           maxAyat: 128 },
  { no:  17, nama: "Al-Isra'",          maxAyat: 111 },
  { no:  18, nama: "Al-Kahf",           maxAyat: 110 },
  { no:  19, nama: "Maryam",            maxAyat:  98 },
  { no:  20, nama: "Ta-Ha",             maxAyat: 135 },
  { no:  21, nama: "Al-Anbiya'",        maxAyat: 112 },
  { no:  22, nama: "Al-Hajj",           maxAyat:  78 },
  { no:  23, nama: "Al-Mu'minun",       maxAyat: 118 },
  { no:  24, nama: "An-Nur",            maxAyat:  64 },
  { no:  25, nama: "Al-Furqan",         maxAyat:  77 },
  { no:  26, nama: "Ash-Shu'ara'",      maxAyat: 227 },
  { no:  27, nama: "An-Naml",           maxAyat:  93 },
  { no:  28, nama: "Al-Qasas",          maxAyat:  88 },
  { no:  29, nama: "Al-'Ankabut",       maxAyat:  69 },
  { no:  30, nama: "Ar-Rum",            maxAyat:  60 },
  { no:  31, nama: "Luqman",            maxAyat:  34 },
  { no:  32, nama: "As-Sajdah",         maxAyat:  30 },
  { no:  33, nama: "Al-Ahzab",          maxAyat:  73 },
  { no:  34, nama: "Saba'",             maxAyat:  54 },
  { no:  35, nama: "Fatir",             maxAyat:  45 },
  { no:  36, nama: "Ya-Sin",            maxAyat:  83 },
  { no:  37, nama: "As-Saffat",         maxAyat: 182 },
  { no:  38, nama: "Sad",               maxAyat:  88 },
  { no:  39, nama: "Az-Zumar",          maxAyat:  75 },
  { no:  40, nama: "Ghafir",            maxAyat:  85 },
  { no:  41, nama: "Fussilat",          maxAyat:  54 },
  { no:  42, nama: "Ash-Shura",         maxAyat:  53 },
  { no:  43, nama: "Az-Zukhruf",        maxAyat:  89 },
  { no:  44, nama: "Ad-Dukhan",         maxAyat:  59 },
  { no:  45, nama: "Al-Jathiyah",       maxAyat:  37 },
  { no:  46, nama: "Al-Ahqaf",          maxAyat:  35 },
  { no:  47, nama: "Muhammad",          maxAyat:  38 },
  { no:  48, nama: "Al-Fath",           maxAyat:  29 },
  { no:  49, nama: "Al-Hujurat",        maxAyat:  18 },
  { no:  50, nama: "Qaf",               maxAyat:  45 },
  { no:  51, nama: "Adh-Dhariyat",      maxAyat:  60 },
  { no:  52, nama: "At-Tur",            maxAyat:  49 },
  { no:  53, nama: "An-Najm",           maxAyat:  62 },
  { no:  54, nama: "Al-Qamar",          maxAyat:  55 },
  { no:  55, nama: "Ar-Rahman",         maxAyat:  78 },
  { no:  56, nama: "Al-Waqi'ah",        maxAyat:  96 },
  { no:  57, nama: "Al-Hadid",          maxAyat:  29 },
  { no:  58, nama: "Al-Mujadila",       maxAyat:  22 },
  { no:  59, nama: "Al-Hashr",          maxAyat:  24 },
  { no:  60, nama: "Al-Mumtahanah",     maxAyat:  13 },
  { no:  61, nama: "As-Saf",            maxAyat:  14 },
  { no:  62, nama: "Al-Jumu'ah",        maxAyat:  11 },
  { no:  63, nama: "Al-Munafiqun",      maxAyat:  11 },
  { no:  64, nama: "At-Taghabun",       maxAyat:  18 },
  { no:  65, nama: "At-Talaq",          maxAyat:  12 },
  { no:  66, nama: "At-Tahrim",         maxAyat:  12 },
  { no:  67, nama: "Al-Mulk",           maxAyat:  30 },
  { no:  68, nama: "Al-Qalam",          maxAyat:  52 },
  { no:  69, nama: "Al-Haqqah",         maxAyat:  52 },
  { no:  70, nama: "Al-Ma'arij",        maxAyat:  44 },
  { no:  71, nama: "Nuh",               maxAyat:  28 },
  { no:  72, nama: "Al-Jinn",           maxAyat:  28 },
  { no:  73, nama: "Al-Muzzammil",      maxAyat:  20 },
  { no:  74, nama: "Al-Muddaththir",    maxAyat:  56 },
  { no:  75, nama: "Al-Qiyamah",        maxAyat:  40 },
  { no:  76, nama: "Al-Insan",          maxAyat:  31 },
  { no:  77, nama: "Al-Mursalat",       maxAyat:  50 },
  { no:  78, nama: "An-Naba'",          maxAyat:  40 },
  { no:  79, nama: "An-Nazi'at",        maxAyat:  46 },
  { no:  80, nama: "'Abasa",            maxAyat:  42 },
  { no:  81, nama: "At-Takwir",         maxAyat:  29 },
  { no:  82, nama: "Al-Infitar",        maxAyat:  19 },
  { no:  83, nama: "Al-Mutaffifin",     maxAyat:  36 },
  { no:  84, nama: "Al-Inshiqaq",       maxAyat:  25 },
  { no:  85, nama: "Al-Buruj",          maxAyat:  22 },
  { no:  86, nama: "At-Tariq",          maxAyat:  17 },
  { no:  87, nama: "Al-A'la",           maxAyat:  19 },
  { no:  88, nama: "Al-Ghashiyah",      maxAyat:  26 },
  { no:  89, nama: "Al-Fajr",           maxAyat:  30 },
  { no:  90, nama: "Al-Balad",          maxAyat:  20 },
  { no:  91, nama: "Ash-Shams",         maxAyat:  15 },
  { no:  92, nama: "Al-Layl",           maxAyat:  21 },
  { no:  93, nama: "Ad-Duha",           maxAyat:  11 },
  { no:  94, nama: "Ash-Sharh",         maxAyat:   8 },
  { no:  95, nama: "At-Tin",            maxAyat:   8 },
  { no:  96, nama: "Al-'Alaq",          maxAyat:  19 },
  { no:  97, nama: "Al-Qadr",           maxAyat:   5 },
  { no:  98, nama: "Al-Bayyinah",       maxAyat:   8 },
  { no:  99, nama: "Az-Zalzalah",       maxAyat:   8 },
  { no: 100, nama: "Al-'Adiyat",        maxAyat:  11 },
  { no: 101, nama: "Al-Qari'ah",        maxAyat:  11 },
  { no: 102, nama: "At-Takathur",       maxAyat:   8 },
  { no: 103, nama: "Al-'Asr",           maxAyat:   3 },
  { no: 104, nama: "Al-Humazah",        maxAyat:   9 },
  { no: 105, nama: "Al-Fil",            maxAyat:   5 },
  { no: 106, nama: "Quraysh",           maxAyat:   4 },
  { no: 107, nama: "Al-Ma'un",          maxAyat:   7 },
  { no: 108, nama: "Al-Kawthar",        maxAyat:   3 },
  { no: 109, nama: "Al-Kafirun",        maxAyat:   6 },
  { no: 110, nama: "An-Nasr",           maxAyat:   3 },
  { no: 111, nama: "Al-Masad",          maxAyat:   5 },
  { no: 112, nama: "Al-Ikhlas",         maxAyat:   4 },
  { no: 113, nama: "Al-Falaq",          maxAyat:   5 },
  { no: 114, nama: "An-Nas",            maxAyat:   6 },
]

/** Set nama-nama surah valid untuk validasi server-side. */
export const VALID_SURAH_NAMES = new Set(SURAH_LIST.map((s) => s.nama))

/** Lookup maxAyat berdasarkan nama surah. */
export function getMaxAyat(namaSurah: string): number {
  return SURAH_LIST.find((s) => s.nama === namaSurah)?.maxAyat ?? 0
}
